[package]
name = "webdav-handler"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]

[lib]
name = "webdav_handler"
path = "src/lib.rs"

[dependencies]
hyper = "0.10"
log = "0.4.6"
serde = "1.0.84"
serde_derive = "1.0.84"
xml-rs = "0.8.0"
url = "1.7.2"
regex = "1.1.0"
time = "0.1.41"
sha2 = "0.8.0"
xmltree = "0.8.0"
uuid = { version = "0.7.1", features = ["v4"] }
lazy_static = "1.2.0"
mime_guess = "1.8.6"
htmlescape = "0.3.1"
percent-encoding = "1.0.1"

# for bin/webdav_handler.rs
env_logger = "0.6.0"
clap = "2.32.0"

# for localfs.rs
filetime = "0.2.4"
libc = "0.2.46"

