[package]
name = "webdav-handler"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "webdav_handler"
path = "src/lib.rs"

[dependencies]
bytes = "0.4.11"
futures01 = { package = "futures", version = "0.1.25" }
futures = { package = "futures-preview", version = "0.3.0-alpha.13", features = ["io-compat"] }
htmlescape = "0.3.1"
http = "0.1.16"
hyperx = "0.14.0"
lazy_static = "1.3.0"
libc = "0.2.50"
log = "0.4.6"
mime_guess = "1.8.6"
percent-encoding = "1.0.1"
regex = "1.1.2"
serde = "1.0.89"
serde_derive = "1.0.89"
threadpool = "1.7.1"
time = "0.1.42"
tokio-threadpool = "0.1.12"
url = "1.7.2"
uuid = { version = "0.7.2", features = ["v4"] }
xml-rs = "0.8.0"
xmltree = "0.8.0"
parking_lot = "0.7.1"
lru = "0.1.13"

[dev-dependencies]
actix = "0.7.9"
actix-web = "0.7.18"
clap = "2.32.0"
env_logger = "0.6.0"
failure = "0.1.5"
hyper = "0.12.25"
tokio = "0.1.16"
tokio-current-thread = "0.1.5"

