[package]
name = "webdav-handler"

# When releasing to crates.io:
# - Update html_root_url in src/lib.rs
# - Update CHANGELOG.md.
# - Run ./generate-readme
# - Create git tag v0.x.y
version = "0.2.0-alpha.3"

readme = "README.md"
description = "handler for the HTTP and Webdav protocols with filesystem backend"
documentation = "https://docs.rs/webdav-handler"
repository = "https://github.com/miquels/webdav-handler-rs"
homepage = "https://github.com/miquels/webdav-handler-rs"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["webdav"]
categories = ["web-programming"]

[lib]
name = "webdav_handler"
path = "src/lib.rs"

[dependencies]
bytes = "0.5.2"
futures = "0.3.1"
htmlescape = "0.3.1"
http = "0.2.0"
http-body = "0.3.0"
lazy_static = "1.4.0"
libc = "0.2.66"
log = "0.4.8"
lru = "0.4.1"
mime_guess = "2.0.1"
parking_lot = "0.10.0"
percent-encoding = "1.0.1"
pin-project = "0.4.6"
regex = "1.3.1"
serde = "1.0.103"
serde_derive = "1.0.103"
tokio = { version = "0.2.3", features = ["rt-core", "rt-threaded", "blocking"] }
time = "0.1.42"
url = "2.1.0"
uuid = { version = "0.8.1", features = ["v4"] }
xml-rs = "0.8.0"
xmltree = "0.8.0"

# Alpha / git versions.
headers = { git = "https://github.com/hyperium/headers" }
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
#actix-web = "2.0.0-alpha.1"
clap = "2.33.0"
env_logger = "0.7.1"
failure = "0.1.6"
hyper = { git = "https://github.com/hyperium/hyper" }
tokio = { version = "0.2.3", features = ["full"] }

