[package]
name = "webdav-handler"

# When releasing to crates.io:
# - Update html_root_url in src/lib.rs
# - Update CHANGELOG.md.
# - Run ./generate-readme
# - Create git tag v0.x.y
version = "0.2.0-alpha.4"

readme = "README.md"
description = "handler for the HTTP and Webdav protocols with filesystem backend"
documentation = "https://docs.rs/webdav-handler"
repository = "https://github.com/miquels/webdav-handler-rs"
homepage = "https://github.com/miquels/webdav-handler-rs"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["webdav"]
categories = ["web-programming"]

[lib]
name = "webdav_handler"
path = "src/lib.rs"

[features]
default = []
actix-compat = [ "actix-web", "actix-rt" ]
warp-compat = [ "warp", "hyper" ]
all = [ "actix-compat", "warp-compat" ]

[[example]]
name = "actix"
required-features = [ "actix-compat" ]

[[example]]
name = "hyper"
required-features = [ "hyper" ]

[[example]]
name = "warp"
required-features = [ "warp-compat" ]

[[example]]
name = "sample-litmus-server"
required-features = [ "hyper" ]

[dependencies]
bytes = "0.5.5"
futures = "0.3.5"
handlebars = "3.1.0"
headers = "0.3.2"
htmlescape = "0.3.1"
http = "0.2.1"
http-body = "0.3.1"
lazy_static = "1.4.0"
libc = "0.2.71"
log = "0.4.8"
lru = "0.5.2"
mime_guess = "2.0.3"
parking_lot = "0.10.2"
percent-encoding = "1.0.1"
pin-project = "0.4.22"
pin-utils = "0.1.0"
regex = "1.3.9"
tokio = { version = "0.2.21", features = ["rt-core", "rt-threaded", "blocking"] }
time = { version = "0.2.16", default-features = false }
url = "2.1.1"
uuid = { version = "0.8.1", features = ["v4"] }
xml-rs = "0.8.3"
xmltree = "0.10.0"

hyper = { version = "0.13.6", optional = true }
warp = { version = "0.2.3", optional = true }
actix-web = { version = "2.0", optional = true }
actix-rt = { version = "1.1", optional = true }

[dev-dependencies]
clap = "2.33.1"
env_logger = "0.7.1"
tokio = { version = "0.2.21", features = ["full"] }
hyper = "0.13.6"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
features = ["full"]

