[package]
name = "webdav-handler"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]

[lib]
name = "webdav_handler"
path = "src/lib.rs"

[dependencies]
hyper = "0.10"
log = "0.3"
serde = "1.0"
serde_derive = "1.0"
xml-rs = "0.7"
url = "1.6"
regex = "0.2"
time = "0.1"
sha2 = "0.7"
xmltree = "0.8"
uuid = { version = "0.4", features = ["use_std", "v4"] }
lazy_static = "1.0"
mime_guess = "1.8"
htmlescape = "0.3.1"

# for bin/webdav_handler.rs
env_logger = "0.4"
clap = "2.29.4"

# for localfs.rs
filetime = "0.1"
libc = "0.2"

